check-certificate=false
console-log-level=notice
continue
download-result=hide
enable-color=false
file-allocation=none
max-concurrent-downloads=20
max-connection-per-server=16
min-split-size=1M
split=12
summary-interval=0
